[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false

# RPC endpoints
[rpc_endpoints]
base = "${BASE_RPC_URL}"

# Etherscan configuration
[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Testing
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15